- lib/src/excel.dart
- lib/src/sheet/sheet.dart
- test/excel_test.dart
I would like to add this into the repo.
We are using excel primarily for importing purposes, so I had always convert into json format and I would like to have this in this library itself. 
Additionally I added `toString()` to `Excel` and `Sheet`, so a print will show more than `Instance of '#'`
Question:
When I cloned "_isContain()" was not defined? 
Remove this line after/before merge.
> Convert | Implement 'toJson()' and 'toString()'

- README.md
Added a ' for correct code highlighting in pub.dev and for correct code when copying and pasting
> Fixed README Code issue in "Find and Replace"

- lib/excel.dart
- lib/src/parser/parse.dart
- lib/src/save/save_file.dart
- lib/src/sheet/header_footer.dart
- lib/src/sheet/sheet.dart
- test/excel_test.dart
This pull request adds support for the reading/writing headers and footers (headerFooter element). The HeaderFooter class exposes the raw content of the odd/even header/footer elements. All formatting [codes](https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_evenHeader_topic_ID0EJKY4.html#topic_ID0EJKY4) must be handled manually.
> Add support for headers and footers

- README.md
I installed the excel package according to the documentation, but the caching problem with the current `2.0.0-null-safety` version archive is causing me some problems, maybe we can update the version number in the documentation to the latest.
#91  #88
> docs: update the package version number in the documentation

- README.md
Removes the README section where the dependency constraints are explained, as these issues have been fixed 2 months ago. This part can safely be removed, and this change should also be reflected on the README on pub.dev.
> Remove section of incompatible dependencies

- lib/src/sheet/sheet.dart
Currently using `findAndReplace` returns the number of theoretical replacements but doesn't actually replace anything. That is because the value of `replaceAll(sourceRegx, target.toString())` inside `findAndReplace` isn't assigned back to the sheet data, making the call practically a noop.
> Assign return value of replaceAll

- lib/src/sharedStrings/shared_strings.dart
Hey so this is a quick simple fix for everyone who is having issues with cells containing the wrong data.
Overall, while quick, HashCode should not be used as a Key as they are non-unique.  To keep some semblance of speed we can continue to have it verify through hash, but if they run into the same data then it would need to verify through the string data itself.
Yes this will slow things down on large excels, but that is when it is needed the most.
Some tests I was doing with my real world data took my decode times from ~5s to ~5.5s and in my larger file from ~9.2s to 9.9s. Again to be clear, the "faster" files were corrupted by this issue so being faster in the case meant nothing.
I think this relates to a few different errors people are getting and likely a lot of errors that are going …
> On hashCode equal, verify using string data

- example/excel_custom_size.dart
- lib/src/save/save_file.dart
- lib/src/sheet/sheet.dart
- lib/src/utilities/constants.dart
Dear justkawal,
I was recently writing a project that involves setting the width and height of an exported excel table. During my exploration of the available methods, I came across the `setColWidth` function. However, upon further investigation of the related issues and PRs, I noticed that the `setRowHeight` method, which was intended to be added in #99, seemed to have been unintentionally removed or overlooked. So,  I invested some time into fixing that. And at the mean time, I added a way to set default column width and row height.
I hope that proves valuable to the project. Thank you for your time and consideration.
> Add setRowHeight & a way to set default column width and row height

- lib/src/excel.dart
- lib/src/parser/parse.dart
some lib creating excel file will use absolute path in Relationship, such as go-excelize.
in this case, cell value can not be read correctly.
> support sharedStrings absolute path

- lib/src/parser/parse.dart
- lib/src/save/self_correct_span.dart
- lib/src/sheet/sheet.dart
- lib/src/utilities/span.dart
- Use `CellIndex` data type instead of `List<int>` if possible
- Avoid unnecessary use of private variables
- Force the Span constructor to receive required fields
> Refactor Span

- CHANGELOG.md
- lib/src/sheet/cell_index.dart
- lib/src/sheet/formula.dart
- lib/src/sheet/sheet.dart
- lib/src/utilities/fast_list.dart
- Replace `assert` check with non-null constraints
- Avoid unnecessary use of `late` keyword
- Avoid unnecessary use of private variables
> Refactor CellIndex, FastList and Formula

- lib/src/parser/parse.dart
Fixes #234
A typo made the background color parsing return always null
> Fix background color parsing

- lib/src/parser/parse.dart
- lib/src/sheet/header_footer.dart
Fixes `XmlNode.text` being deprecated since `xml 6.3.0`.
https://pub.dev/packages/xml/changelog#630
> Fix XML deprecated properties

- test/excel_test.dart
Test have been randomly failing for some time.
Turns out it is because some tests are marked as async when they shouldn't, which can cause a race condition on the deletion of the tmp folder.
> Fix race condition in tests

- lib/src/number_format/num_format.dart
Fixes a parsing exception for excel numeric cells with numbers like 0.001, which are saved as scientific notation "1E-3"
> Scientific notation number parsing

- lib/src/save/save_file.dart
This is an update to @FauconSpartiate's  PR #280 targeting version 4 of the library. This also fixes a bug where the number of sized columns was used at the end instead of the index of the last sized column.
Fixes #265
> Fixed column widths not being updated.

- lib/src/save/save_file.dart
- test/excel_test.dart
when no numFmts are found in styles.xml, customNumFormats are inserted at the very beginnig of styles.xml
now it seems to be inserted at a proper place
> fix customNumFormats position in styles.xml

- lib/src/sheet/sheet.dart
in the insert row function of the sheet there is a bug as the two cases new row index > max rows and not are switched.
> Fix of wrong calculation of new max rows if inserting a new row

- lib/src/sheet/sheet.dart
After a new row is added, the data is moved, but inside the data row for each column the rowIndex is stored but not updated.
> fix after insert new row, data is not written to the correct row

- lib/src/sheet/sheet.dart
there are deletions done on _sheetData but later on this is overwritten by _data, therefore these operations are useless.
> delete row small performance improvement

- pubspec.yaml
The use of a fixed version for "archive" will make it impossible to use the "excel" package with recent packages or projects using a newer version of "archive".
> v4.0.6 - pubspec.yaml (archive: ^3.4.10)

- pubspec.yaml
bumped archive version to 3.6.1 for compatibility with newest flutter version
> changed archive version to 3.6.1
